version: '3'

services:
  
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=subtitles_db
      - MYSQL_USER=subtitles_user
      - MYSQL_PASSWORD=password123

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      
  subtitle_search:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mysql
      - elasticsearch
  

volumes:
  mysql_data:
  elasticsearch_data:
