version: '3'

services:
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    environment:
      - cluster.name=docker-cluster
      - node.name=node-1
      - discovery.seed_hosts=node-1
      - cluster.initial_master_nodes=node-1
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - network1
      
  subtitle_search:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch
    networks:
      - network1

networks:
  network1:
    driver: bridge  

volumes:
  elasticsearch_data:
